#!/usr/bin/env bash
# generate ssl certificate with certbot

sudo apt-get update
sudo apt-get upgrade

# install let's Encypt package
sudo apt install -y letsencrypt

# check if certbot is running
service certbot.timer status

#generate ssl command
certbot certonly --standalone --agree-tos --preferred-challenges http -d unixcop.com --register-unsafely-without-email


#  Your account credentials have been saved in your Certbot
#  configuration directory at /etc/letsencrypt. You should make a
#  secure backup of this folder now. This configuration directory will
#  also contain certificates and private keys obtained by Certbot so
#  making regular backups of this folder is ideal.
