#!/usr/bin/env bash
# configure HAproxy load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen webapp 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\tserver 237-web-01 3.239.99.139:80 check\n\tserver 237-web-02 44.201.95.79 check" /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg
sudo service haproxy start