#!/usr/bin/env bash
# Does the following:
    # Create a file /var/run/my_process.pid containing the script PID.
    # Displays "To infinity and beyond" indefinitely
    # Displays "I hate the kill command" upon receiving a SIGTERM
    # Displays "Y U no love me?!" upon receiving a SIGINT
    # Deletes the file /var/run/my_process.pid  and terminates upon
    # receiving a SIGQUIT or SIGTERM.

echo $$ >> /var/run/myscript.pid

trap 'echo I hate the kill command; rm -f /var/run/myscript.pid; exit 1' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit 1' SIGQUIT
trap "echo Y U no lpve me?!" SIGINT

while true;
    do
        echo "To infinity and beyond"
        sleep 2;
done

