#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
# only displays:
    # username
    # user id
    # Home directory path for the user

while read $passwd; do
    echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"